// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcMVoqSTyJGNCQAgkRZ_Ske8bo9Apmf8',
    appId: '1:610185883352:web:1fad6e9ed4db30fb77b1ad',
    messagingSenderId: '610185883352',
    projectId: 'jasaku-app-251a8',
    authDomain: 'jasaku-app-251a8.firebaseapp.com',
    storageBucket: 'jasaku-app-251a8.firebasestorage.app',
    measurementId: 'G-D0TWBKQ3Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQsKfYx0YBWLQFsnVXZfXYlAMCLtmU-s',
    appId: '1:610185883352:android:2b4041e972a505cb77b1ad',
    messagingSenderId: '610185883352',
    projectId: 'jasaku-app-251a8',
    storageBucket: 'jasaku-app-251a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEpUl94dPqH-KqXmGrqASVoBIDI3f1ZM',
    appId: '1:610185883352:ios:b72178f0e463f0c177b1ad',
    messagingSenderId: '610185883352',
    projectId: 'jasaku-app-251a8',
    storageBucket: 'jasaku-app-251a8.firebasestorage.app',
    iosBundleId: 'com.jasaku.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEpUl94dPqH-KqXmGrqASVoBIDI3f1ZM',
    appId: '1:610185883352:ios:92752800f72b34f377b1ad',
    messagingSenderId: '610185883352',
    projectId: 'jasaku-app-251a8',
    storageBucket: 'jasaku-app-251a8.firebasestorage.app',
    iosBundleId: 'com.example.jasakuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpcMVoqSTyJGNCQAgkRZ_Ske8bo9Apmf8',
    appId: '1:610185883352:web:cfdb883c807ccc2077b1ad',
    messagingSenderId: '610185883352',
    projectId: 'jasaku-app-251a8',
    authDomain: 'jasaku-app-251a8.firebaseapp.com',
    storageBucket: 'jasaku-app-251a8.firebasestorage.app',
    measurementId: 'G-Z9GHE6R1CC',
  );
}
